name: wechat
version: 1.4.0
summary: A better WeChat client based on Electronic
description:
  The is a Electronic wrapper of wechat web frontend.
  https://github.com/geeeeeeeeek/electronic-wechat
confinement: devmode

apps:
  electronic-wechat:
    command: desktop-launch ${SNAP}/electronic-wechat
    plugs: [unity7, network, network-bind, home]

parts:
  electronic-wechat:
    plugin: electronic
    source: https://github.com/geeeeeeeeek/electronic-wechat.git
    source-branch: v1.4.0
    source-type: git
    after:
      - desktop-gtk3
  env:
    plugin: nil
    stage-packages:
      - gconf2
      - gconf-service
      - libasound2
      - libcap2
      - libgcrypt20
      - libgtk2.0-0
      - libnotify4
      - libnspr4
      - libnss3
      - libudev1
      - libxss1
      - libxtst6
      - python
      - unity-gtk2-module
      - xdg-utils
      - fonts-droid-fallback
    after: 
      - electronic-wechat

